### ISSUE TITLE
logdir doesn't exist

### ISSUE THREAD

**Issue by bobpaul** [arjunkc/scanner-scripts#1]
I'm getting this error when I try to use your scripts:

```
-- Journal begins at Sat 2021-12-04 21:28:39 CST. --
Dec 18 11:51:42 brscan-skey[332242]:     if logfile:
Dec 18 11:51:42 brscan-skey[332242]: NameError: name 'logfile' is not defined
Dec 18 11:51:42 brscan-skey[332242]: Traceback (most recent call last):
Dec 18 11:51:42 brscan-skey[332242]:   File "/opt/brother/scanner/brscan-skey/script/batchscan.py", line 84, in <module>
Dec 18 11:51:42 brscan-skey[332242]:     args = parse_arguments()
Dec 18 11:51:42 brscan-skey[332242]:   File "/opt/brother/scanner/brscan-skey/script/batchscan.py", line 56, in parse_arguments
Dec 18 11:51:42 brscan-skey[332242]:     os.makedirs(args.logdir)
Dec 18 11:51:42 brscan-skey[332242]:   File "/usr/lib/python3.9/os.py", line 225, in makedirs
Dec 18 11:51:42 brscan-skey[332242]:     mkdir(name, mode)
```

The bug is in `batchscan.py`. the following lines:

```
default_logdir = '/tmp' + r'brscan/'
default_outdir = '/tmp' + r'brscan/'
```
should be changed to 
```
default_logdir = os.path.join('/tmp', 'brscan')
default_outdir = os.path.join('/tmp', 'brscan')
```

**Comment by arjunkc** [comment]
Thanks, fixed.
